### ISSUE TITLE
 sentence = " ".join(line["tokens"]) ， KeyError: 'tokens'

### ISSUE THREAD

**Issue by tongbao96** [jiangguochaoGG/ToNER#1]
Dear Author, Thank you for your impressive work！
When I tried to run this code, I got a problem:

In the file: flat_recall_train.py, the format of input  raw_data as follows: 

{'input': 'List all named entities of the type [miscellaneous, organization, location, person].\nText: EU rejects German call to boycott British lamb .\nEntities of type [] may exist in text', 'target': '[(organization, EU), (miscellaneous, German), (miscellaneous, British)]', 'labels': [{'name': 'organization', 'value': 'EU'}, {'name': 'miscellaneous', 'value': 'German'}, {'name': 'miscellaneous', 'value': 'British'}], 'raw_index': 0}

sentence = ‘’.join(line[‘tokens’]) gives an error: KeyError: ‘tokens’, 

as if there doesn't seem to be a key for 'tokens' in this json format？

I'm not sure if I'm missing some data processing steps, looking forward to your reply!

**Comment by jiangguochaoGG** [comment]
Thanks for your comment!
From the raw_data information you provided, it seems that the dataset you are using is not in the format I use. From https://huggingface.co/datasets/conll2003, every data item has keys ['chunk_tags', 'id', 'ner_tags', 'pos_tags', 'tokens']. 'tokens' can be combined into 'sentence' for subsequent use.

**Comment by tongbao96** [comment]
thanks for your reply, when i load dataset like this:
dataset = load_dataset('conll2003',cache_dir="../path",trust_remote_code=True)
it works! ! thanks again!
